### ISSUE TITLE
Missing License Information in file Mod FIle: smooth-scrolling-everywhere-1.3

### ISSUE THREAD

**Issue by Mark1ed** [shedaniel/SmoothScrollingEverywhere#37] opened 2022-07-10 13:52 UTC
[crash-2022-07-10_16.43.01-fml.txt](https://github.com/shedaniel/SmoothScrollingEverywhere/files/9079193/crash-2022-07-10_16.43.01-fml.txt)

**Comment by Delfite** [comment] 2022-07-22 15:13
@shedaniel So when are you gonna fix this?

**Comment by shedaniel** [comment] 2022-07-22 15:20
Duplicate of #14

**Closed as completed by shedaniel** 2022-07-22 15:20 UTC
