### ISSUE TITLE
Missing License, Cannot be used

### ISSUE THREAD

**Issue by WelpSTudent** [shedaniel/SmoothScrollingEverywhere#18] opened 2021-04-07 17:56 UTC

**Comment by vizthex123** [comment] 2021-06-15 01:03
same here, quite annoying. I'm on the Forge version.

**Comment by JetpackRescue** [comment] 2022-02-02 19:30
IT'S STILL A PROBLEM. YOUR MOD DOESN'T WORK ON 1.16.5

**Comment by shedaniel** [comment] 2022-07-22 15:20
Duplicate of https://github.com/shedaniel/SmoothScrollingEverywhere/issues/14

**Closed by shedaniel** 2022-07-22 15:20 UTC
